name: flutter_base
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  audioplayers: ^0.20.1
  auto_size_text: ^3.0.0
  bloc: ^8.0.3
  bubble_bottom_bar: ^2.0.0
  cupertino_icons: ^1.0.4
  dio: ^4.0.4
  draggable_fab: ^0.1.4
  draggable_floating_button: ^0.1.1
  draggable_widget: ^2.0.0
  easy_localization: ^3.0.0
  equatable: ^2.0.3
  expandable: null
  fab_circular_menu: ^1.0.0
  file: ^6.1.2
  flutter:
    sdk: flutter
  flutter_audio_recorder2: ^0.0.2
  flutter_bloc: ^8.0.1
  flutter_offline: ^2.0.0
  fluttertoast: ^8.0.8
  get: ^4.6.1
  google_fonts: ^2.2.0
  image_picker: ^0.8.4+5
  infinite_scroll_pagination: ^3.1.0
  internet_connection_checker: ^0.0.1+3
  intl: ^0.17.0
  just_waveform: ^0.0.2
  path_provider: null
  pinput: ^1.2.0
  quran_widget_flutter:
    path: ../quran_flutter_widget
  record: ^3.0.2
  rxdart: ^0.27.3
  search_page: ^2.0.0+1
  shared_preferences: ^2.0.12
  sqflite: ^2.0.2
  dependencies:
  file_picker: ^4.5.1
  just_audio: ^0.9.20

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.jpg"

flutter_native_splash:
  image: assets/images/splash.png
  color: "#fede65"
  fill: true

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/audio/waveform.mp3
    - assets/audio/waveform.wave
    - assets/fonts/allah_names.ttf
    - assets/fonts/Cairo/Cairo-Black.ttf
    - assets/fonts/Cairo/Cairo-Bold.ttf
    - assets/fonts/Cairo/Cairo-ExtraLight.ttf
    - assets/fonts/Cairo/Cairo-Light.ttf
    - assets/fonts/Cairo/Cairo-Regular.ttf
    - assets/fonts/Cairo/Cairo-SemiBold.ttf
    - assets/fonts/Cairo/OFL.txt
    - assets/fonts/El_Messiri/ElMessiri-Bold.ttf
    - assets/fonts/El_Messiri/ElMessiri-Medium.ttf
    - assets/fonts/El_Messiri/ElMessiri-Regular.ttf
    - assets/fonts/El_Messiri/ElMessiri-SemiBold.ttf
    - assets/fonts/El_Messiri/OFL.txt
    - assets/fonts/hafs_smart_08.ttf
    - assets/fonts/Quicksand/Quicksand-Bold.ttf
    - assets/fonts/Quicksand/Quicksand-Light.ttf
    - assets/fonts/Quicksand/Quicksand-Medium.ttf
    - assets/fonts/Quicksand/Quicksand-Regular.ttf
    - assets/fonts/Quicksand/Quicksand-SemiBold.ttf
    - assets/fonts/quran_karim.ttf
    - assets/fonts/uthmanic_bazzi1_ver07.ttf
    - assets/fonts/uthmanic_doori1ver09.ttf
    - assets/fonts/uthmanic_hafs1_ver15.ttf
    - assets/fonts/uthmanic_hafs1_ver17.ttf
    - assets/fonts/uthmanic_qaloon1_ver10.ttf
    - assets/fonts/uthmanic_qumbul1_ver07.ttf
    - assets/fonts/uthmanic_shouba1_ver08.ttf
    - assets/fonts/uthmanic_soosi1_ver09.ttf
    - assets/fonts/uthmanic_warsh1_ver10.ttf
    - assets/fonts/uthmantn1ver10_0.ttf
    - assets/fonts/uthmantn8b_ver10.ttf
    - assets/icons/add.png
    - assets/icons/bubble.png
    - assets/icons/coming_soon.png
    - assets/icons/discussion.png
    - assets/icons/done.png
    - assets/icons/download.png
    - assets/icons/empty.png
    - assets/icons/facebook_icon.png
    - assets/icons/filter.png
    - assets/icons/google_icon.png
    - assets/icons/helal.png
    - assets/icons/home.png
    - assets/icons/language.png
    - assets/icons/like.png
    - assets/icons/like2.png
    - assets/icons/mail.png
    - assets/icons/makkah.png
    - assets/icons/medina.png
    - assets/icons/pause.png
    - assets/icons/play.png
    - assets/icons/play2.png
    - assets/icons/profile.png
    - assets/icons/quality.png
    - assets/icons/quality2.png
    - assets/icons/quran.png
    - assets/icons/quran2.png
    - assets/icons/quran3.png
    - assets/icons/quran4.png
    - assets/icons/reading.png
    - assets/icons/search.png
    - assets/icons/share.png
    - assets/icons/teacher.png
    - assets/icons/twitter_icon.png
    - assets/icons/user.png
    - assets/images/ads.jpeg
    - assets/images/ads2.jpg
    - assets/images/back1.jpg
    - assets/images/back2.png
    - assets/images/facebook_icon.png
    - assets/images/icon.jpg
    - assets/images/login_backGround.png
    - assets/images/page016.png
    - assets/images/splash.png
    - assets/images/twitter_icon.png
    - assets/images/user_img.png
    - assets/images/user_img2.jpg
    - assets/lang/ar.json
    - assets/lang/en.json
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo/Cairo-Light.ttf

    - family: ElMessiri
      fonts:
        - asset: assets/fonts/El_Messiri/ElMessiri-Regular.ttf
        - asset: assets/fonts/El_Messiri/ElMessiri-Bold.ttf
        - asset: assets/fonts/El_Messiri/ElMessiri-Medium.ttf

    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand/Quicksand-Bold.ttf
        - asset: assets/fonts/Quicksand/Quicksand-Medium.ttf
        
    - family: HafsSmart
      fonts:
        - asset: assets/fonts/hafs_smart_08.ttf 

    - family: QuranKarim
      fonts:
        - asset: assets/fonts/quran_karim.ttf

    - family: Bazzi1
      fonts:
        - asset: assets/fonts/uthmanic_bazzi1_ver07.ttf

    - family: Doori
      fonts:
        - asset: assets/fonts/uthmanic_doori1ver09.ttf

    - family: Hafs17
      fonts:
        - asset: assets/fonts/uthmanic_hafs1_ver17.ttf 
