name: flutter_base
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  audioplayers: ^0.20.1
  bloc: ^8.0.2
  bubble_bottom_bar: ^2.0.0
  cupertino_icons: ^1.0.4
  dio: ^4.0.4
  #dio_cache_interceptor: ^3.2.4
  draggable_fab: ^0.1.4
  draggable_floating_button: ^0.1.1
  draggable_widget: ^2.0.0
  easy_localization: ^3.0.0
  equatable: ^2.0.3
  fab_circular_menu: ^1.0.0
  file: ^6.1.2
  flutter:
    sdk: flutter
  flutter_audio_recorder2: ^0.0.2
  flutter_bloc: ^8.0.1
  flutter_offline: ^2.0.0
  fluttertoast: ^8.0.8
  get: ^4.6.1
  google_fonts: ^2.2.0
  image_picker: ^0.8.4+5
  internet_connection_checker: ^0.0.1+3
  intl: ^0.17.0
  just_waveform: ^0.0.2
  path_provider: ^2.0.9
  pinput: ^1.2.0
  quran_widget_flutter:
    path: ../quran_flutter_widget
  record: ^3.0.2
  rxdart: ^0.27.3
  search_page: ^2.0.0+1
  shared_preferences: ^2.0.12
  sqflite: ^2.0.2
  toast: ^0.1.5

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.jpg"

flutter_native_splash:
  image: assets/images/splash.png
  color: "#fede65"
  fill: true

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/lang/
    - assets/icons/
    - assets/images/
    - assets/audio/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo/Cairo-Light.ttf

    - family: ElMessiri
      fonts:
        - asset: assets/fonts/El_Messiri/ElMessiri-Regular.ttf
        - asset: assets/fonts/El_Messiri/ElMessiri-Bold.ttf
        - asset: assets/fonts/El_Messiri/ElMessiri-Medium.ttf

    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand/Quicksand-Bold.ttf
        - asset: assets/fonts/Quicksand/Quicksand-Medium.ttf
