name: flutter_base
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  bloc: ^8.0.2
  bubble_bottom_bar: ^2.0.0
  cupertino_icons: ^1.0.4
  dio: ^4.0.4
  easy_localization: ^3.0.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_offline: ^2.0.0
  fluttertoast: ^8.0.8
  get: ^4.6.1
  google_fonts: ^2.2.0
  image_picker: ^0.8.4+5
  internet_connection_checker: ^0.0.1+3
  intl: ^0.17.0
  just_waveform: ^0.0.2
  rxdart: ^0.27.3
  shared_preferences: ^2.0.12
  sqflite: ^2.0.2
  sms_autofill: ^2.2.0
  flutter_native_splash: ^2.0.2

flutter_native_splash:
  image: assets/images/splash.png
  color: "#fede65"

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/lang/
    - assets/icons/
    - assets/images/
    - assets/audio/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo/Cairo-Light.ttf

    - family: ElMessiri
      fonts:
        - asset: assets/fonts/El_Messiri/ElMessiri-Regular.ttf
        - asset: assets/fonts/El_Messiri/ElMessiri-Bold.ttf
        - asset: assets/fonts/El_Messiri/ElMessiri-Medium.ttf

    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand/Quicksand-Bold.ttf
        - asset: assets/fonts/Quicksand/Quicksand-Medium.ttf
