/// Generated by AssetsRefGenerator on 2022/03/19
// ignore_for_file: constant_identifier_names

class Res {
  static const String add = 'assets/icons/add.png';
  static const String ads = 'assets/images/ads.jpeg';
  static const String ads2 = 'assets/images/ads2.jpg';
  static const String allah_names = 'assets/fonts/allah_names.ttf';
  static const String ar = 'assets/lang/ar.json';
  static const String assets_fonts_El_Messiri_OFL =
      'assets/fonts/El_Messiri/OFL.txt';
  static const String assets_images_facebook_icon =
      'assets/images/facebook_icon.png';
  static const String assets_images_twitter_icon =
      'assets/images/twitter_icon.png';
  static const String back1 = 'assets/images/back1.jpg';
  static const String back2 = 'assets/images/back2.png';
  static const String bubble = 'assets/icons/bubble.png';
  static const String Cairo_Black = 'assets/fonts/Cairo/Cairo-Black.ttf';
  static const String Cairo_Bold = 'assets/fonts/Cairo/Cairo-Bold.ttf';
  static const String Cairo_ExtraLight =
      'assets/fonts/Cairo/Cairo-ExtraLight.ttf';
  static const String Cairo_Light = 'assets/fonts/Cairo/Cairo-Light.ttf';
  static const String Cairo_Regular = 'assets/fonts/Cairo/Cairo-Regular.ttf';
  static const String Cairo_SemiBold = 'assets/fonts/Cairo/Cairo-SemiBold.ttf';
  static const String coming_soon = 'assets/icons/coming_soon.png';
  static const String discussion = 'assets/icons/discussion.png';
  static const String done = 'assets/icons/done.png';
  static const String download = 'assets/icons/download.png';
  static const String ElMessiri_Bold =
      'assets/fonts/El_Messiri/ElMessiri-Bold.ttf';
  static const String ElMessiri_Medium =
      'assets/fonts/El_Messiri/ElMessiri-Medium.ttf';
  static const String ElMessiri_Regular =
      'assets/fonts/El_Messiri/ElMessiri-Regular.ttf';
  static const String ElMessiri_SemiBold =
      'assets/fonts/El_Messiri/ElMessiri-SemiBold.ttf';
  static const String empty = 'assets/icons/empty.png';
  static const String en = 'assets/lang/en.json';
  static const String facebook_icon = 'assets/icons/facebook_icon.png';
  static const String filter = 'assets/icons/filter.png';
  static const String google_icon = 'assets/icons/google_icon.png';
  static const String hafs_smart_08 = 'assets/fonts/hafs_smart_08.ttf';
  static const String helal = 'assets/icons/helal.png';
  static const String home = 'assets/icons/home.png';
  static const String icon = 'assets/images/icon.jpg';
  static const String language = 'assets/icons/language.png';
  static const String like = 'assets/icons/like.png';
  static const String like2 = 'assets/icons/like2.png';
  static const String login_backGround = 'assets/images/login_backGround.png';
  static const String mail = 'assets/icons/mail.png';
  static const String makkah = 'assets/icons/makkah.png';
  static const String medina = 'assets/icons/medina.png';
  static const String OFL = 'assets/fonts/Cairo/OFL.txt';
  static const String page016 = 'assets/images/page016.png';
  static const String pause = 'assets/icons/pause.png';
  static const String play = 'assets/icons/play.png';
  static const String play2 = 'assets/icons/play2.png';
  static const String profile = 'assets/icons/profile.png';
  static const String quality = 'assets/icons/quality.png';
  static const String quality2 = 'assets/icons/quality2.png';

  static const String Quicksand_Bold =
      'assets/fonts/Quicksand/Quicksand-Bold.ttf';
  static const String Quicksand_Light =
      'assets/fonts/Quicksand/Quicksand-Light.ttf';
  static const String Quicksand_Medium =
      'assets/fonts/Quicksand/Quicksand-Medium.ttf';
  static const String Quicksand_Regular =
      'assets/fonts/Quicksand/Quicksand-Regular.ttf';
  static const String Quicksand_SemiBold =
      'assets/fonts/Quicksand/Quicksand-SemiBold.ttf';

  static const String quran = 'assets/icons/quran.png';
  static const String quran2 = 'assets/icons/quran2.png';
  static const String quran3 = 'assets/icons/quran3.png';
  static const String quran4 = 'assets/icons/quran4.png';
  static const String quran_karim = 'assets/fonts/quran_karim.ttf';
  static const String reading = 'assets/icons/reading.png';
  static const String search = 'assets/icons/search.png';
  static const String share = 'assets/icons/share.png';
  static const String splash = 'assets/images/splash.png';
  static const String teacher = 'assets/icons/teacher.png';
  static const String twitter_icon = 'assets/icons/twitter_icon.png';
  static const String user = 'assets/icons/user.png';
  static const String user_img = 'assets/images/user_img.png';
  static const String user_img2 = 'assets/images/user_img2.jpg';
  static const String uthmanic_bazzi1_ver07 =
      'assets/fonts/uthmanic_bazzi1_ver07.ttf';
  static const String uthmanic_doori1ver09 =
      'assets/fonts/uthmanic_doori1ver09.ttf';
  static const String uthmanic_hafs1_ver15 =
      'assets/fonts/uthmanic_hafs1_ver15.ttf';
  static const String uthmanic_hafs1_ver17 =
      'assets/fonts/uthmanic_hafs1_ver17.ttf';
  static const String uthmanic_qaloon1_ver10 =
      'assets/fonts/uthmanic_qaloon1_ver10.ttf';
  static const String uthmanic_qumbul1_ver07 =
      'assets/fonts/uthmanic_qumbul1_ver07.ttf';
  static const String uthmanic_shouba1_ver08 =
      'assets/fonts/uthmanic_shouba1_ver08.ttf';
  static const String uthmanic_soosi1_ver09 =
      'assets/fonts/uthmanic_soosi1_ver09.ttf';
  static const String uthmanic_warsh1_ver10 =
      'assets/fonts/uthmanic_warsh1_ver10.ttf';
  static const String uthmantn1ver10_0 = 'assets/fonts/uthmantn1ver10_0.ttf';
  static const String uthmantn8b_ver10 = 'assets/fonts/uthmantn8b_ver10.ttf';
  //static const String waveform = "assets/audio/waveform.mp3";
  static const String waveform = 'assets/audio/waveform.wave';
}
